import { Types } from 'mongoose';

export interface IAppliedApplication {
  /** Reference to the targeted TuitionJob record */
  job: Types.ObjectId;

  /** Reference to the profile of the applying Teacher */
  applicant: Types.ObjectId;

  /** Current processing funnel stage of the application */
  status: 'applied' | 'shortlisted' | 'rejected' | 'hired' | 'cancelled';

  /** Audit indicator mapping how the application profile was created */
  source: 'website_application' | 'admin_sourced';

  /** Reference to the Admin managing this sourced pipeline mapping, if applicable */
  managed_by?: Types.ObjectId | null;

  /** Automated timestamp fields generated by Mongoose configuration settings */
  createdAt?: Date;
  updatedAt?: Date;
}
